# Generated by Django 5.2.6 on 2025-10-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='surname',
            field=models.CharField(null=True),
        ),
    ]
