# Generated by Django 5.2.6 on 2025-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='facultycolor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
