# Generated by Django 5.2.6 on 2025-10-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_faculty_facultycolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
